import './globals.css'
import type { Metadata } from 'next'
import Providers from './providers'
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  title: 'tanstack query 13',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1
  },
  icons: '/favicon.ico'
}
