import Providers from './providers'
import Link from 'next/link'
import type { Metadata } from 'next'
import RootStyleRegistry from './emotion'
import './globals.css'
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head />
      <body>
        <RootStyleRegistry>
          <Providers>
            <Link href={'/'}>Home</Link>
            <Link href={'/supabase'}>Supabase</Link>
            {children}
          </Providers>
        </RootStyleRegistry>
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  title: 'tanstack query 13',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1
  }
}
